apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-deployment # nome do deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-api # tag para selecionar os pods desda implantação
  template:
    metadata:
      labels:
        app: web-api # tag aplicada no deploy
    spec:
      containers:
      - name: web-api-container
        image: web-api-image:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
